### ISSUE TITLE
editable virtual pages

### ISSUE THREAD

**Issue by werewrwere** [zely-js/zely#265]
**Problem**: Currently `virtualPage` cannot be modified or removed.
If virtualPages can be modified and removed, it is expected that the zely app can be infinitely extended.

It will be developed in the following form:

```ts
const page = virtual.create("/hello.ts", []);

virtual.set(page, [GET(() => "Hello World!")]);
virtual.delete(page);
```

`zely.virtual` will replace the existing `createVirtualPage()`.

**Comment by do4ng** [comment]
Closed
